os:
    - linux
    - osx

language: rust
rust:
    - nightly
    - stable

cache:
  cargo

install:
    - | [ $TRAVIS_OS_NAME = linux ] && export CXX="g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # recent version of cmake
    packages:
    - gcc-4.8
    - g++-4.8 # required to compile glslang
    - clang
    - cmake
    - cmake-data

script:
    - git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
    - travis_wait cargo test --all -j 1
    - cd examples
    - cargo build
    - cd .. # this is very important or else the below `cargo publish` will fail

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_OS_NAME = linux ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vk-sys/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_OS_NAME = linux ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_OS_NAME = linux ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-win/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_OS_NAME = linux ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-shaders/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_OS_NAME = linux ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-shader-derive/Cargo.toml
