[package]
name = "glsl-to-spirv"
version = "0.1.7"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>", "The vulkano contributors"]
repository = "https://github.com/vulkano-rs/vulkano"
description = "Deprecated. Use shaderc-rs instead."
license = "MIT/Apache-2.0"
build = "build/build.rs"
categories = ["rendering::graphics-api"]

[dependencies]
tempfile = "3"

[build-dependencies]
cmake = "0.1.27"
sha2 = "0.7"
